name:                to-do
version:             0.1.0.0
github:              "kigsmtua/haskelltopia/tree/master/to-do"
license:             MIT
author:              "John Kiragu"
maintainer:          "mutuakiragu@gmail.com"
copyright:           "2018 John Kiragu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kigsmtua/haskelltopia/blob/master/to-do/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  to-do-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - to-do
    - optparse-applicative

tests:
  to-do-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - to-do
